### ISSUE TITLE
Do we use Angular?

### ISSUE THREAD

**Issue by ketanbhatt** [ketanbhatt/habits#1]
@TigerApps IMO Angular looks like an overkill atm. Lets begin with vanilla JS. Thoughts?

**Comment by WhiteHatArpit** [comment]
Considering templating and modularity provided by AngularJS, working on boiler plate Angular looks to be easier than trying to convert messy VanillaJS to AngularJS at later run.

**Comment by ketanbhatt** [comment]
But we are going to introduce complexity unnecessarily. I was going through it, and realised that we won't need Angular at all.

Our use case is to simple, angular will only bloat it. 
Maybe we will use it later when we feel the need to, right now it makes sense not to.

**Comment by WhiteHatArpit** [comment]
ok! lets roll with vanilla JS, jquery.

**Comment by ketanbhatt** [comment]
I will avoid jquery too for the beginning :dancer: lets use things only when we need them!
