### ISSUE TITLE
App closes with the settings window, home doesn't show up

### ISSUE THREAD

**Issue by WhiteHatArpit** [ketanbhatt/habits#13]
After pressing the 'Enter Name' button, the settings window gets closed and the home window doesn't get drawn, the app shuts down.
Possible cause: App closes down because the last window is closed (doesnt happen in OS X)

**Comment by WhiteHatArpit** [comment]
@ketanbhatt 
check out this flow:

On app start, if userName present: open home
otherwise, open settings. 
   if closed: close app (destruction of last window will close the app itself)
   else if userName entered: redraw home; close settings

when settings is called from home:
    if closed: close settings (home will stay as it was)
   else if userName entered: redraw home; close settings

**Comment by ketanbhatt** [comment]
:+1:
