### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by WhiteHatArpit** [ketanbhatt/habits#25]
Date should be stored in which format?
Remember that anytime of the day we would only need y m d.

**Comment by ketanbhatt** [comment]
@TigerApps Very standard. All date/time will be in epoch (seconds).

When we show it to the user, then we can convert it easily. Epoch will make the conversion simple.

**Comment by ketanbhatt** [comment]
Store in Epoch.
Get relevant date like:

``` javascript
const d = new Date();
const t = new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12).getTime()
```

:dancers: @TigerApps
