### ISSUE TITLE
Get basic understanding of Electron

### ISSUE THREAD

**Issue by ketanbhatt** [ketanbhatt/habits#6]
[This](https://medium.com/developers-writing/building-a-desktop-application-with-electron-204203eeb658#.onzcvlkgx) is the only article I read and then couldn't wait any longer. Directly jumped into execution :laughing: 

You cant review https://github.com/ketanbhatt/habits/pull/5 until you complete this issue.

Let me know if you found any other good resource.

**Comment by WhiteHatArpit** [comment]
https://github.com/atom/electron/tree/master/docs/api
https://github.com/sindresorhus/awesome-electron

**Comment by WhiteHatArpit** [comment]
https://github.com/mawie81/whatsdesktop
https://github.com/steventhanna/proton

2 small but nice projects.

**Comment by ketanbhatt** [comment]
Whatsapp!! Sexy!

**Comment by WhiteHatArpit** [comment]
https://github.com/hokein/electron-sample-apps
Small stuff to explore the Electron api.

**Comment by WhiteHatArpit** [comment]
https://github.com/teesloane/snippet-bar
good stuff
