### ISSUE TITLE
Decide how to store habits and their data

### ISSUE THREAD

**Issue by ketanbhatt** [ketanbhatt/habits#7]
What is the most suitable way to store data in `Electron` is still a mystery to us. 
Figure out the database needs of the app and explore possible solutions.
- [x] How are we modelling our data
- [x] What database do we use and why?

**Comment by ketanbhatt** [comment]
First of all, we were being foolish. We don't need a db for electron specifically, we can use whatever we would use with node! :dancers: 

## DB Design
1. No relationships among the data so NoSQL
2. Thinking of storing name and other things we won't query in a `json` like already done.
3. Storing habits and their commits in a database
4. **Collections:** `habits, commits`. 
5. **habits:** `title, desc, created_at, type (pos/neg), weight`
6. **commits:** `date: {habit: count, habit: count}` _Love my brain for this_ :dancer:

## What do we use

LokiJs seems to be good :dart:

**Comment by ketanbhatt** [comment]
@TigerApps ^

**Comment by WhiteHatArpit** [comment]
LokiJS is looking good. We only need to keep the activity of last month (or some other fixed amount). Other data can be stored in as file or thrown away. 
Can even add some compression while storing in file if we go that way.

**Comment by ketanbhatt** [comment]
Yo, can be done later on!

**Comment by ketanbhatt** [comment]
@TigerApps I was thinking, why not use orchestrate? It will reduce our pain of dealing with javascript objects and stuff. Or better, we can use firebase. What say?

**Comment by ketanbhatt** [comment]
Nope, will have to login and stuff :x:

**Comment by WhiteHatArpit** [comment]
Need it local. Don't need to use web.
Check how Snippets Bar is storing Snippets.
